services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minimall-app
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod

      SPRING_DATASOURCE_URL: jdbc:mysql://minimall-rds.cbiss8uq8eb8.eu-north-1.rds.amazonaws.com:3306/minimall?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: minimall
      SPRING_DATASOURCE_PASSWORD: minimall1234

      TZ: Asia/Seoul
    ports:
      - "8080:8080"
