services:
  app:
    image: openjdk:21
    container_name: minimall-app
    working_dir: /app
    volumes:
      - ../:/app
    ports:
      - "8080:8080"
    command: sh -c "./gradlew bootRun"
    depends_on:
      - db

  db:
    image: mysql:8.4.4
    container_name: minimall-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minimall
      MYSQL_USER: minimall
      MYSQL_PASSWORD: minimall
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
