services:
  db-test:
    image: mysql:8.4.4
    container_name: minimall-db-test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minimall_test
    ports:
      - "3307:3306"
    volumes:
      - db_data_test:/var/lib/mysql
    networks:
      - test-net

  app-test:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: minimall-app-test
    environment:
      SPRING_PROFILES_ACTIVE: test
      DB_HOST: db-test
      DB_PORT: 3306
      DB_NAME: minimall_test
      DB_USER: root
      DB_PASSWORD: root
    depends_on:
      - db-test
    networks:
      - test-net

volumes:
  db_data_test:

networks:
  test-net:
